### ISSUE TITLE
[Feature Request] Typeahead

### ISSUE THREAD

**Issue by peterskim12** [swiftype/app-search-reference-ui-react#26]
It'd be great if the reference UI had typeahead. Maybe a config parameter with a list of fields queried for typeahead?

**Comment by JasonStoltz** [comment]
This has now be added.

There is a configuration in `engine.json` that lets you specify which fields to suggest on, `querySuggestFields`.

If accessing from the App Search Dashboard, it will automatically be configured to use all Text fields.
